# config/settings.yaml

urls:
  okta: https://filevine.okta.com
  solarwinds: https://api.samanage.com
  lucidchart: https://users.lucid.app/scim/v2

okta:
  domain: filevine.okta.com

google:
  domain: filevine.com
  admin_email: cody@filevine.com

onepassword:
  paths:
    okta_token: "op://IT/okta-api-token/password"
    solarwinds_token: "op://IT/samanage-api-token/password"
    samanage_token: "op://IT/samanage-api-token/password"
    slack_token: "op://IT/slack-bot-token/password"
    microsoft_tenant_id: "op://IT/microsoft-graph-api/tenant_id"
    microsoft_client_id: "op://IT/microsoft-graph-api/username"
    microsoft_client_secret: "op://IT/microsoft-graph-api/credential"
    exchange_tenant_id: "op://IT/microsoft-graph-api/tenant_id"
    exchange_app_id: "op://IT/microsoft-graph-api/username"
    exchange_cert_thumbprint: "op://IT/microsoft-graph-api/certificate_thumbprint"
    google_service_account: "op://IT/google-workspace-service-account/credential"
    zoom_api_key: "op://IT/Zoom_API_Key/password"
    zoom_api_secret: "op://IT/Zoom_API_Secret/password"
    zoom_account_id: "op://IT/Zoom_Account_ID/password"
    domo_client_id: "op://IT/domo-api/Domo Client ID"
    domo_client_secret: "op://IT/domo-api/Domo Client Secret"
    lucid_bearer_token: "op://IT/lucid_bearer_token/password"
    synqprox_username: "op://IT/SynQ Prox/username"
    synqprox_password: "op://IT/SynQ Prox/password"

# Windows Credential Manager settings
credential_manager:
  service_account_name: "JML Service Account"

solarwinds:
  base_url: "https://api.samanage.com"
  subdomain: it
  catalog_item_id: 1198997
  state_ids:
    - 827236
    - 827237
    - 827238
    - 827239
    - 827240
    - 868561
    - 912210
    - 918367
    - 925284
    - 1214303
    - 1303729
    - 1388495
  active_states:
    - "New"
    - "Assigned" 
    - "Auto-Assigned"
  max_pages: 40
  per_page: 100
  max_workers: 30